imports:
    - php


filter:
    excluded_paths:
        - 'test/*'
checks:
    php:
        code_rating: true
        duplication: true
        align_assignments: true
        avoid_fixme_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_perl_style_comments: true
        avoid_todo_comments: true
        avoid_unnecessary_concatenation: true
        classes_in_camel_caps: true
        encourage_postdec_operator: true
        encourage_single_quotes: true
        fix_line_ending: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        simplify_boolean_return: true
        return_doc_comments: true
        remove_extra_empty_lines: true
        properties_in_camelcaps: true
        prefer_while_loop_over_for_loop: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        return_doc_comment_if_not_inferrable: true
        function_in_camel_caps: true
        no_goto: true

coding_style:
    php: {  }
    
tools:
    external_code_coverage: true
