imports:
    - php

filter:
    excluded_paths: [test/*]

checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        duplication: true

tools:
    external_code_coverage: true
